language: groovy

arch: amd64    # routes to a full VM
os: 
  - linux
  - osx
dist: trusty  

jobs:
  include:
    - os: osx
      osx_image: xcode9.3

env:
  global:
    - GRADLE_OPTS=-Xmx1524m

jdk:
  - oraclejdk8
  - oraclejdk11
  - oraclejdk14
  - oraclejdk15
  - openjdk8
  - openjdk11
  - openjdk14
  - openjdk15
  - openjdk16

  
matrix:
  allow_failures:
    - os: osx
    - jdk: openjdk16


script:
  - java -version
  - ./gradlew -version
  - ./gradlew --stop
  - ./gradlew --refresh-dependencies clean check test assemble -Dscan --info
  - ./distro/prank predict -f ./distro/test_data/2W83.pdb
